# Generated by Django 4.2.6 on 2023-10-29 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0002_alter_jugador_celjug_alter_jugador_telmadre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrp', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrp', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='socio',
        ),
        migrations.AddField(
            model_name='jugador',
            name='tipoSocio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jugadores.tiposocio'),
        ),
    ]
