# Generated by Django 4.2.6 on 2023-10-29 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0003_tipodivision_tiposocio_remove_jugador_socio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='div',
        ),
        migrations.AddField(
            model_name='jugador',
            name='idDiv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jugadores.tipodivision'),
        ),
        migrations.AlterField(
            model_name='tipodivision',
            name='descrp',
            field=models.CharField(max_length=3),
        ),
    ]
