# Generated by Django 4.2.6 on 2023-10-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0004_remove_jugador_div_jugador_iddiv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodivision',
            name='descrp',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
