# Generated by Django 4.2.6 on 2023-11-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0005_alter_tipodivision_descrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='dniValidado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
