# Generated by Django 4.2.6 on 2023-10-22 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoJor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fechaJor', models.DateTimeField(blank=True, null=True)),
                ('obs', models.TextField()),
                ('tipoJor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asistencias.tipojor')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('fechaCompletado', models.DateTimeField(blank=True, null=True)),
                ('idJor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencias.jornada')),
                ('idJug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jugadores.jugador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
