# Generated by Django 4.2.6 on 2023-10-29 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0004_remove_jugador_div_jugador_iddiv_and_more'),
        ('asistencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciasTotales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalAsist', models.IntegerField(default=0)),
                ('idAsist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencias.asistencia')),
                ('tipoDiv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugadores.tipodivision')),
                ('tipoSoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugadores.tiposocio')),
            ],
        ),
    ]
