# Generated by Django 4.2.6 on 2023-10-29 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0005_alter_tipodivision_descrp'),
        ('asistencias', '0002_asistenciastotales'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciasTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalAsist', models.IntegerField(default=0)),
                ('idJor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencias.jornada')),
                ('tipoDiv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jugadores.tipodivision')),
                ('tipoSoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugadores.tiposocio')),
            ],
        ),
        migrations.DeleteModel(
            name='AsistenciasTotales',
        ),
    ]
