# Generated by Django 4.2.6 on 2023-11-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0003_asistenciastotal_delete_asistenciastotales'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='tarde',
            field=models.BooleanField(default=False),
        ),
    ]
